title: Gamze Bozkurt Omar
logo: https://github.com/gamzebb/portfolio/edit/main/Screenshot%202025-04-27%20123422.jpg
description: Data Analyst | MSc. Nuclear Engineer
show-downloads: False
theme: jekyll-theme-minimal
